version: '3.3'
services:
  db:
    image: postgres:alpine
    volumes:
      - source: db-dev-data
        target: /var/lib/postgresql/data
        type: volume

  redis:
    image: redis:alpine
    volumes:
      - source: redis-data
        target: /data
        type: volume

  app:
    stdin_open: true
    tty: true
    build: .
    command: /bin/bash -c "./bin/setup && rails s -b '0.0.0.0'"
    links:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/app:delegated
    env_file:
      - .env

  sidekiq:
    tty: true
    build: .
    command: bundle exec sidekiq -C ./config/sidekiq.yaml
    links:
      - db
      - redis
    volumes:
      - .:/app:delegated
    env_file:
      - .env




volumes:
  db-dev-data:
  redis-data:
